### ISSUE TITLE
학습 설정 값 오류 수정, Train 동작 제어 기능 추가

### ISSUE THREAD

**Issue by Choi-Dongjin** [Choi-Dongjin/ProjectAI#11]
## description
> 학습 옵션중 Validation Ratio값 백분율로 표시된 값이 학습에 적용시 소수로 적용되도록 수정 필요. 
> Train 동작중 일시 정지, 정지, 시작, 제어가 가능하도록 기능 추가.
> Cad Image - Heatmap 표기 되도록 수정.
## todo
- [x] Validation Ratio값 소수로 적용 가능하도록 수정
- [x] 학습된 모델 선택시 Heatmap 표기가 가능하도록 수정
- [x] Train 동작 일시 정지
- [x] Train 동작 정지
- [x] Train 취소
