### ISSUE TITLE
학습 취소 기능, 프로그램 시작시 지연문제 해결

### ISSUE THREAD

**Issue by Choi-Dongjin** [Choi-Dongjin/ProjectAI#15]
## description
> 학습 취소 기능 수정 (fix)
> 프로그램 시작시 지연 문제 확인후 수정 (fix)
## todo
- [x] 학습 취소 기능 수정
- [x] 프로그램 시작시 지연 문제 확인
- [x] ㅡ로그램 시작시 지연 문제 수정

**Comment by Choi-Dongjin** [comment]
프로그램 시작시 지연 문제 임시 처리
workspace 용량 확인 지연
```
CustomIOMainger.DirSize -> 수정 필요
```
, Json 데이터 읽어오기 지연
    프로젝트가 커지면 파일 읽어오기 지연 발생.
    지연 함수 
```
1. MainFormLoad.MainFormLoad -> MainFormLoad.WorkSpaceEarlyDataSet,
2. MainFormLoad.MainFormShown
```
