### ISSUE TITLE
프로그램의 불필요한 부분 및 개선 사항 수정

### ISSUE THREAD

**Issue by naranghae** [Choi-Dongjin/ProjectAI#26]
## description
> 프로그램의 불필요한 부분 및 개선 사항을 수정합니다.
## todo
- [x] 불필요한 UI 제거 (drawing menu bar)
- [x] fill flood 다른 cell 누르면 초기화
- [x] image zoom시 다른 cell을 눌렀을 때 유지
